### ISSUE TITLE
500 internal server error

### ISSUE THREAD

**Issue by Fi-tz** [evereux/pycatia-tools#2]
evereux edit:

Missing details from details provided in posts below.

### Server message:

```
500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

```

### System versions:

* python 3.12.3
* CATIA V5 R2016.

**Comment by evereux** [comment]
My first thought is that you don't have CATIA V5 running, which if this was the case, is what it would say on the 500 error page:

```
500 Internal Server Error: Could not access COM object. Is CATIA V5 running? 
```

Can you provide more information please.

**Comment by Fi-tz** [comment]
I run my catia application at first,the run pycatia tool ,at this moment,“cmd” pop out,and I got this link(http://127.0.0.1:5578 and I click the link combined with control key and the web shows this notice

**Comment by Fi-tz** [comment]
![image](https://github.com/user-attachments/assets/8d2e3b08-bbdb-47c8-b150-b755270f1058)
 As this picture

**Comment by Fi-tz** [comment]
Bro,do you have any idea?

**Comment by evereux** [comment]
Hmm. Can't think what would have caused that. Can you provide the full traceback (error log) from the terminal window. 

Also, what version of python are you using and what version of CATIA V5?

Should be able to figure it out with this information.

**Comment by Fi-tz** [comment]
![image](https://github.com/user-attachments/assets/ca90694a-074b-43f5-a511-d27e205f4eb7)
![image](https://github.com/user-attachments/assets/09a8aaa3-c1e6-4c91-9c0c-028d01c7e3e3)
![image](https://github.com/user-attachments/assets/1661094f-d30b-4069-ba51-7229545941b9)

The version of apps concerned with this issue just uploaded,bro ,could you figure this out ?!

**Comment by evereux** [comment]
Please don't post pictures when text will suffice. 😃 

I suspect the problem here is that the COM server hasn't been registered. This can happen due to the installation process missing this step (no idea why, but I have seen this happen) or you're using a portable version that doesn't do this.

To fix this you can either:

* Reinstall CATIA V5
* Manually register the com server. See the bottom of this page with regards to steps on how to do this: https://pycatia.readthedocs.io/en/latest/installation.html. I think you only need do `cnext.exe /regserver` though. No need to specify `-env <env_file> -direnv <path_to_env_file>` (I need to update that page).

**Comment by Fi-tz** [comment]
Okay，next time i would try only texts ,and I will check the method you mentioned later and I will let you know result,thx for replying!

**Comment by Fi-tz** [comment]
Hey Bro,after i did this 
Suggestion [3,General]: 找不到命令 cnext.exe，但它确实存在于当前位置。默认情况下，Windows PowerShell 不会从当前位置加载 命令。如果信任此命令，请改为键入“.\cnext.exe”。有关详细信息，请参阅 "get-help about_Command_Precedence"。
PS D:\Program Files\Dassault Systemes\B26\win_b64\code\bin> .\cnext.exe /regserver
PS D:\Program Files\Dassault Systemes\B26\win_b64\code\bin>

and i tried to open pycaita-tool ,yet it still not work ,by the way ,i didn`t clear how to specify this step 
"2. run the following command after replacing <env_file> and <path_to_env_file> with the appropriate values:
cnext.exe /regserver -env <env_file> -direnv <path_to_env_file>"
 could you give me a example what the exactly command that i should type into the "cmd" window is

[2024-09-05 21:29:56,977] ERROR in app: Exception on /htmx/document/object [GET]
Traceback (most recent call last):
  File "C:\Users\Jaqen\Desktop\PYCATI~1.1DE\PYCATI~1.1DE\win32com\client\dynamic.py", line 84, in _GetGoodDispatch
pywintypes.com_error: (-2147221005, '无效的类字符串', None, None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Jaqen\Desktop\PYCATI~1.1DE\PYCATI~1.1DE\flask\app.py", line 1473, in wsgi_app
  File "C:\Users\Jaqen\Desktop\PYCATI~1.1DE\PYCATI~1.1DE\flask\app.py", line 882, in full_dispatch_request
  File "C:\Users\Jaqen\Desktop\PYCATI~1.1DE\PYCATI~1.1DE\flask\app.py", line 0, in handle_user_exception
  File "C:\Users\Jaqen\Desktop\PYCATI~1.1DE\PYCATI~1.1DE\flask\app.py", line 880, in full_dispatch_request
  File "C:\Users\Jaqen\Desktop\PYCATI~1.1DE\PYCATI~1.1DE\flask\app.py", line 865, in dispatch_request
  File "C:\Users\Jaqen\Desktop\PYCATI~1.1DE\PYCATI~1.1DE\application\views\htmx\document_queries.py", line 19, in htmx_document_object
  File "C:\Users\Jaqen\Desktop\PYCATI~1.1DE\PYCATI~1.1DE\application\pycatia_scripts\the_document.py", line 22, in __init__
  File "C:\Users\Jaqen\Desktop\PYCATI~1.1DE\PYCATI~1.1DE\application\pycatia_scripts\com_objects.py", line 32, in get_app_object
  File "C:\Users\Jaqen\Desktop\PYCATI~1.1DE\PYCATI~1.1DE\pycatia\base_interfaces\base_application.py", line 12, in catia_application
  File "C:\Users\Jaqen\Desktop\PYCATI~1.1DE\PYCATI~1.1DE\win32com\client\__init__.py", line 118, in Dispatch
  File "C:\Users\Jaqen\Desktop\PYCATI~1.1DE\PYCATI~1.1DE\win32com\client\dynamic.py", line 104, in _GetGoodDispatchAndUserName
  File "C:\Users\Jaqen\Desktop\PYCATI~1.1DE\PYCATI~1.1DE\win32com\client\dynamic.py", line 86, in _GetGoodDispatch
pywintypes.com_error: (-2147221005, '无效的类字符串', None, None)
127.0.0.1 - - [05/Sep/2024 21:29:56] "GET /htmx/document/object HTTP/1.1" 500 -

**Comment by evereux** [comment]
```
PS D:\Program Files\Dassault Systemes\B26\win_b64\code\bin> .\cnext.exe /regserver
```

This is correct.

Might be worth rebooting the PC so Windows properly reloads the registry changes.



Also, search your registry for the string 'CATIA.Application' to make sure it exists. Should do now though.

![2024-09-05 15_31_06-500 internal server error · Issue #2 · evereux_pycatia-tools — Mozilla Firefox](https://github.com/user-attachments/assets/c158ea1e-97e9-4bd1-b5e7-8c18ca8256ef)

The error you're getting is related to pycatia trying to initialise the COM interface, not with pycatia-tools itself.

Try the following to prove this:

```
PS C:\Users\evereux\github\pycatia-tools> .\env\Scripts\activate
(env) PS C:\Users\evereux\github\pycatia-tools> python
Python 3.11.8 (tags/v3.11.8:db85d51, Feb  6 2024, 22:03:32) [MSC v.1937 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from pycatia import catia
>>> caa = catia()
>>>
```

This should throw the same base error. I don't know why though. 🤷 Might be worth posting to the pycatia github repository if this is the case as it'll get more visibility there.
